// Question Types
// 1. MCQs | Multiple Choice | single
// import europe from './data/Mythologie/europe.jpg'

export const quiz = {
    topic: 'Javascript',
    level: 'Beginner',
    totalQuestions: 8,
    perQuestionScore: 1,

    questions: {
    Mythologie:[
      {
        theme: 'Mythologie pré-chrétienne',
        image: require('./data/Mythologie/europe.jpg'),
        image2: require('./data/Mythologie/europe.jpg'),
        question: 'Quelle personnalité peut lier Minos, Astérion, le Liban, LREM et Jupiter ?',
        choices: ['Ulysse', 'Icare', 'Europe', 'Thésée'],
        type: 'MCQs',
        correctAnswer: 'Europe',
        explication: '',
      },
      {
        theme: 'Mythologie pré-chrétienne',
        image: require('./data/Mythologie/zeus.jpg'),
        image2: require('./data/Mythologie/zeus.jpg'),
        question: 'En combien d\'animaux réels Zeus, s\'est-il métamorphosé ?',
        choices: ['3', '6', '7', '8'],
        type: 'MCQs',
        correctAnswer: '6',
        explication: '',
      },
      {
        theme: 'Mythologie pré-chrétienne',
        image: require('./data/Mythologie/cuchulainn.jpg'),
        image2: require('./data/Mythologie/cuchulainn.jpg'),
        question: 'Que signifie Cuchulainn, héro de la mythologie celtique irlandaise ?',
        choices: ['Chien de Culann', 'Le Cheminant', 'Roi du Connaught', 'Le Gris de Macha'],
        type: 'MCQs',
        correctAnswer: 'Chien de Culann',
        explication: 'Setanta obtient ce nom en tuant le chien du forgeron qui gardait les portes d\'Ulster. Pour son pardon, il devient le chien du forgeron le temps qu\'un autre chien soit dressé',
      },
      {
        theme: 'Mythologie pré-chrétienne',
        image: require('./data/Mythologie/odin.jpg'),
        image2: require('./data/Mythologie/odin2.jpg'),
        question: 'Quel(s) compagnon(s) n\'a(ont) pas entouré Odin ?',
        choices: ['Fenrir', 'Sleipnir', 'Hugin et Munin', 'Guri et Freki'],
        type: 'MCQs',
        correctAnswer: 'Fenrir',
        explication: 'Fenrir est un loup géant, fils de Loki, considéré comme trop puissant par les dieux, il est enchaîné et sera libéré lors du Ragnarök <<Le loup engloutira Odin, et telle sera sa mort. Mais aussitôt, Vidar s\'avancera et posera un pied sur la mâchoire inférieure du loup. [...] D\'une main, il saisira la mâchoire supérieure du loup et lui déchirera la gueule : telle sera la mort du loup.>>',
      },
      {
        theme: 'Mythologie pré-chrétienne',
        image: require('./data/Mythologie/dieux_egyptiens.png'),
        image2: require('./data/Mythologie/dieux_egyptiens.png'),
        question: 'Qui est Sobek ?',
        choices: ['1', '2', '3', '4'],
        type: 'MCQs',
        correctAnswer: '1',
        explication: 'Sobek <<Crocodile>>, dieu de l\'eau et de la fertilité. Dans l\'ordre: Sobek, Anubis dieu de l\'embaumement, Sekhmet, puissance destructrice du Soleil, vengeance de Rê, et Horus, dieu du ciel protecteur des pharaons',
      },
      {
        theme: 'Mythologie pré-chrétienne',
        image: require('./data/Mythologie/Dagon1.jpg'),
        image2: require('./data/Mythologie/Dagon2.jpg'),
        question: 'Lovecraft s\'est inspiré d\'une ancienne divinité syrienne de l\'agriculture pour définir le seigneur des profonds. Quel est son nom ?',
        choices: ['Katulu', 'Dagon', 'Gordon Ramsès', 'Apollon'],
        type: 'MCQs',
        correctAnswer: 'Dagon',
        explication: 'Dagon apparaît généralement comme une figure patriarcale et souveraine du monde divin, et d\'après une étymologie de son nom il est vu comme le dieu du grain et de l\'agriculture',
      },
      {
        theme: 'Mythologie pré-chrétienne',
        image: require('./data/Mythologie/troie.jpg'),
        image2: require('./data/Mythologie/troie.jpg'),
        question: 'Qui n\'a pas participé au siège de Troie après l\'enlèvement d\'Hélène ?',
        choices: ['Ulysse', 'Ménélas', 'Héraclès', 'Hector'],
        type: 'MCQs',
        correctAnswer: 'Héraclès',
        explication: 'Héraclès participe et mène la Première guerre contre Troie. C\'est en sauvant la cité de Troie contre Céto/Céton (monstre marin ou chef de guerre) que le roi de la cité, Laomédon, promet récompense à Héraclès. Or le roi trompa le héro qui au lieu de 2 chevaux divins promis, donna 2 chevaux ordinaires. En colère, Héraclès embarque pour se venger après avoir terminé ses 12 travaux. Héraclès et son armée et ses alliés brulent la cité et sa région et tuent le roi et ses fils.',
      },
      {
        theme: 'Mythologie pré-chrétienne',
        image: require('./data/Mythologie/mithra.jpg'),
        image2: require('./data/Mythologie/mithra.jpg'),
        question: 'Le culte de Mithra est un ancien culte mystère à rite initiatique et hiérarchie des fidèles vers -IIème s. D\'où vient ce culte ?',
        choices: ['Iran', 'Inde', 'Egypte', 'Gaule Narbonaise'],
        type: 'MCQs',
        correctAnswer: 'Iran',
        explication: 'Le culte romain de Mithra est différent des cultes voués au même dieu dans le monde iranien, et à l\'heure actuelle la majorité des spécialistes en déduit qu\'il n\'est pas importé tel quel dans l\'Empire romain mais qu\'il fait l\'objet d\'une création, par le biais d\'un « bricolage » amalgamant éléments mythologiques et rituels perses, grecs et surtout romains.',
      },
    ],
    Martine: [
      {
        theme: 'Martine',
        image: require('./data/Martine/martine_3grammes.jpg'),
        image2: require('./data/Martine/martine_accident.jpg'),
        question: 'Quel est le titre original de cette parodie ?',
        choices: ['Martine fait de la bicyclette', 'Martine, l\'accident', 'Martine en avion', 'Martine dans la forêt'],
        type: 'MCQs',
        correctAnswer: 'Martine, l\'accident',
        explication: '',
      },
      {
        theme: 'Martine',
        image: require('./data/Martine/martine_low-kick.jpg'),
        image2: require('./data/Martine/martine_decouverte.jpg'),
        question: 'Quel est le titre original de cette parodie ?',
        choices: ['Martine dans la forêt', 'Martine à la ferme', 'Martine en classe découverte', 'Martine au cirque'],
        type: 'MCQs',
        correctAnswer: 'Martine en classe découverte',
        explication: '',
      },
      {
        theme: 'Martine',
        image: require('./data/Martine/martine_mahomet.jpg'),
        image2: require('./data/Martine/martine_rentree.jpg'),
        question: 'Quel est le titre original de cette parodie ?',
        choices: ['Martine, vive la rentrée', 'Martine fait du théatre', 'Martine à l\'école', 'Martine, la leçon de dessin'],
        type: 'MCQs',
        correctAnswer: 'Martine, vive la rentrée',
        explication: '',
      },
      {
        theme: 'Martine',
        image: require('./data/Martine/martine_poney.jpg'),
        image2: require('./data/Martine/martine_voisine.jpg'),
        question: 'Quel est le titre original de cette parodie ?',
        choices: ['Martine et les marmitons', 'Martine fait de la cuisine', 'Martine a une étrange voisine', 'Martine a perdu son chien'],
        type: 'MCQs',
        correctAnswer: 'Martine a une étrange voisine',
        explication: '',
      },
      {
        theme: 'Martine',
        image: require('./data/Martine/martine_sncf.jpg'),
        image2: require('./data/Martine/martine_ferme.jpg'),
        question: 'Quel est le titre original de cette parodie ?',
        choices: ['Martine à la ferme', 'Martine à la mer', 'Martine, un mercredi pas comme les autres', 'Martine en classe découverte'],
        type: 'MCQs',
        correctAnswer: 'Martine à la ferme',
        explication: '',
      },
      {
        theme: 'Martine',
        image: require('./data/Martine/martine_unijambiste.jpg'),
        image2: require('./data/Martine/martine_camping.jpg'),
        question: 'Quel est le titre original de cette parodie ?',
        choices: ['Martine baby-sitter', 'Martine et le prince mystérieux', 'Martine, j’adore mon frère !...', 'Martine fait du camping'],
        type: 'MCQs',
        correctAnswer: 'Martine fait du camping',
        explication: '',
      },
      {
        theme: 'Martine',
        image: require('./data/Martine/martine_sodo.jpg'),
        image2: require('./data/Martine/martine_frere.jpg'),
        question: 'Quel est le titre original de cette parodie ?',
        choices: ['Martine va déménager', 'Martine est malade', 'Martine, j\'adore mon frère !...', 'Martine petite maman'],
        type: 'MCQs',
        correctAnswer: 'Martine, j\'adore mon frère !...',
        explication: '',
      },
      {
        theme: 'Martine',
        image: require('./data/Martine/martine_dsk.jpeg'),
        image2: require('./data/Martine/martine_maison.jpg'),
        question: 'Quel est le titre original de cette parodie ?',
        choices: ['Martine à la maison', 'Martine, drôles de fantômes', 'Martine fête maman', 'Martine chez tante Lucie'],
        type: 'MCQs',
        correctAnswer: 'Martine à la maison',
        explication: '',
      },
    ],
    Musique: [
      {
        theme: 'Musique',
        image: require('./data/Musique/metallica-sm.jpg'),
        image2: require('./data/Musique/metallica-sm.jpg'),
        video: '',
        video2: '',
        question: 'Avec quel orchestre symphonique Metallica enregistra l\'album S&M ? ?',
        choices: ['Sydney', 'San Francisco', 'Los Angeles', 'Oslo'],
        type: 'MCQs',
        correctAnswer: 'San Francisco',
        explication: '',
      },
      {
        theme: 'Musique',
        image: require('./data/Musique/rozana.jpg'),
        image2: require('./data/Musique/rozana.jpg'),
        video: 'https://www.dailymotion.com/video/xidhbt',
        video2: 'https://www.dailymotion.com/video/xidhbt',
        question: 'Qui a écrit la chanson originale de cette publicité Rozana ?',
        choices: ['Toto', 'Santana', 'Van Halen', 'Journey'],
        type: 'MCQs',
        correctAnswer: 'Toto',
        explication: '',
      },
      {
        theme: 'Musique',
        image: require('./data/Musique/kaaris.jpg'),
        image2: require('./data/Musique/kaaris.jpg'),
        video: '',
        video2: '',
        question: 'D’oú vient le rappeur Kaaris ?',
        choices: ['Bobigny', 'Aubervilliers', 'Vitry-sur-Seine', 'Sevran'],
        type: 'MCQs',
        correctAnswer: 'Sevran',
        explication: 'Sevran, 93270, Kaaris y fait référence très souvent avec l\'appelation <<2-7-0>>, qui fait donc référence au 93- 270, code postal de la ville de Sevran',
      },
      {
        theme: 'Musique',
        image: require('./data/Musique/gorillaz.jpeg'),
        image2: require('./data/Musique/gorillaz.jpeg'),
        video: '',
        video2: '',
        question: 'Qui qui c\'est ?',
        choices: ['Godzillaz', 'Gorillaz', 'Gojiraz', 'Grosnazi'],
        type: 'MCQs',
        correctAnswer: 'Gorillaz',
        explication: '',
      },
      {
        theme: 'Musique',
        image: require('./data/Musique/pyramid_albums.png'),
        image2: require('./data/Musique/pyramid_albums.png'),
        video: '',
        video2: '',
        question: 'Classez ces albums par sortie chronologique',
        choices: ['1-2-3-4', '3-2-1-4', '2-3-1-4', '4-3-2-1'],
        type: 'MCQs',
        correctAnswer: '1-2-3-4',
        explication: '1977. All\'n All - Earth Wind & Fire, 1984. Powerslave - Iron Maiden, 1989. Pyramid Part One - Pink FLoyd, 2007. Alive - Daft Punk',
      },
      {
        theme: 'Musique',
        image: require('./data/Musique/mannschaft.jpg'),
        image2: require('./data/Musique/mannschaft.jpg'),
        video: 'https://www.youtube.com/watch?v=cgDZN44WpoE&pp=ygUObWFubnNjaGFmdCBzY2g%3D',
        video2: 'https://www.youtube.com/watch?v=cgDZN44WpoE&pp=ygUObWFubnNjaGFmdCBzY2g%3D',
        question: 'Quelle référence culturelle n\'apparait pas dans le morceau "Mannschaft" de SCH et Freeze Corleone ?',
        choices: ['Robocop', 'Ghostrider', 'Goldorak', 'V pour Vendetta'],
        type: 'MCQs',
        correctAnswer: 'Goldorak',
        explication: '0:38 - Robocop, 1:54: V pour Vendetta, 2:18: Ghostrider',
      },
      {
        theme: 'Musique',
        image: require('./data/Musique/zzccmxtp.jpg'),
        image2: require('./data/Musique/zzccmxtp.jpg'),
        video: '',
        video2: 'https://www.youtube.com/watch?v=w7p8BmXw2hI&ab_channel=DotPrime',
        question: 'Quel artiste n\'a pas participé à la ZZCCMXTP ?',
        choices: ['Alkpote', 'Squeezie', 'Le Grand JD', 'Freeze Corleone'],
        type: 'MCQs',
        correctAnswer: 'Freeze Corleone',
        explication: 'Alkpote: Violette et Citronnelle, Squeezie: Adieux les filles, Le Grand JD: JRPG.',
      },
      {
        theme: 'Musique',
        image: require('./data/Musique/mario.jpg'),
        image2: require('./data/Musique/mario.jpg'),
        video: '',
        video2: '',
        question: 'Quel était le véritable nom de Freddie Mercury ?',
        choices: ['John Entwistle', 'Stevie Ray Vaughan', 'Jared Leto', 'Farrokh Bulsara'],
        type: 'MCQs',
        correctAnswer: 'Farrokh Bulsara',
        explication: '',
      },
    ],
    Cinema: [
      {
        theme: 'Cinema',
        image: require('./data/Cinema/annihilation.jpg'),
        image2: require('./data/Cinema/annihilation2.jpg'),
        video: '',
        video2: '',
        question: 'Vrai ou Faux ? Le film "Annihilation" de Alex Garland de 2018 est une adaptation de la nouvelle "The Colour Out of Space" de HP Lovecraft parue en 1927',
        choices: ['Vrai', 'Faux'],
        type: 'MCQs',
        correctAnswer: 'Faux',
        explication: 'Le film est une adaption de la nouvelle "Annihilation" parue en 2014 de Jeff VanderMeer',
      },
      {
        theme: 'Cinema',
        image: require('./data/Cinema/matrix.jpg'),
        image2: require('./data/Cinema/matrix.jpg'),
        video: '',
        video2: '',
        question: 'Dans le premier film "The Matrix", quelle pilule permet de sortir de la matrice ?',
        choices: ['Rouge', 'Bleue'],
        type: 'MCQs',
        correctAnswer: 'Rouge',
        explication: '',
      },
      {
        theme: 'Cinema',
        image: require('./data/Cinema/batman.jpg'),
        image2: require('./data/Cinema/batman2.jpg'),
        video: '',
        video2: '',
        question: 'Quel est le principal vilain de "Batman Returns" ?',
        choices: ['The Joker', 'The Penguin', 'L\'Homme Mystère', 'Bane'],
        type: 'MCQs',
        correctAnswer: 'The Penguin',
        explication: '',
      },
      {
        theme: 'Cinema',
        image: require('./data/Cinema/carpenter.jpg'),
        image2: require('./data/Cinema/carpenter2.jpg'),
        video: '',
        video2: '',
        question: 'Quel film ne fait pas partie de la trilogie de l\'Apocalypse de John Carpenter ?',
        choices: ['Fog (1980)', 'The Thing (1982)', 'Prince des ténèbres (1987)', 'L\'antre de la folie (1995)'],
        type: 'MCQs',
        correctAnswer: 'Fog (1980)',
        explication: '',
      },
      {
        theme: 'Cinema',
        image: require('./data/Cinema/bond.jpg'),
        image2: require('./data/Cinema/bond2.jpg'),
        video: '',
        video2: '',
        question: 'Quel acteur interpréta l\'agent 007 dans le film "Die Another Day ?"',
        choices: ['Daniel Craig', 'Pierce Brosnan', 'George Lazenby', 'Sean Connery'],
        type: 'MCQs',
        correctAnswer: 'Pierce Brosnan',
        explication: '',
      },
      {
        theme: 'Cinema',
        image: require('./data/Cinema/starwars.jpg'),
        image2: require('./data/Cinema/starwars2.jpg'),
        video: '',
        video2: '',
        question: 'Dans quel film, l\'Amiral Ackbar prononce "It\'s a trap !" ?',
        choices: ['Star Wars - Empire strikes back', 'Star Trek - The Final Frontier', 'Star Wars - Rogue One', 'Star Wars - Return of the Jedi'],
        type: 'MCQs',
        correctAnswer: 'Star Wars - Return of the Jedi',
        explication: '',
      },
      {
        theme: 'Cinema',
        image: require('./data/Cinema/shaun.jpg'),
        image2: require('./data/Cinema/shaun.jpg'),
        video: '',
        video2: '',
        question: 'Qui a réalisé le film "Shaun of the Dead" ?',
        choices: ['Richard Donner', 'Edgar Wright', 'Stanley Kubrick', 'Carol Reed'],
        type: 'MCQs',
        correctAnswer: 'Edgar Wright',
        explication: '',
      },
      {
        theme: 'Cinema',
        image: require('./data/Cinema/asylum.jpg'),
        image2: require('./data/Cinema/2012.jpg'),
        video: '',
        video2: '',
        question: 'Quel film n\'a pas été produit par la compagnie The Asylum ?',
        choices: ['2012', 'Halloween Night', 'Transmorphers', 'Titanic II', 'Paranormal Entity', 'Age of the Hobbits', 'Sharknado', 'Alien Convergence ' ],
        type: 'MCQs',
        correctAnswer: '2012',
        explication: '',
      },

    ],
    Biere: [
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/annihilation.jpg'),
      //   image2: require('./data/Biere/annihilation2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Vrai ou Faux ? Le film "Annihilation" de Alex Garland de 2018 est une adaptation de la nouvelle "The Colour Out of Space" de HP Lovecraft parue en 1927',
      //   choices: ['Vrai', 'Faux'],
      //   type: 'MCQs',
      //   correctAnswer: 'Faux',
      //   explication: 'Le film est une adaption de la nouvelle "Annihilation" parue en 2014 de Jeff VanderMeer',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/matrix.jpg'),
      //   image2: require('./data/Biere/matrix.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Dans le premier film "The Matrix", quelle pilule permet de sortir de la matrice ?',
      //   choices: ['Rouge', 'Bleue'],
      //   type: 'MCQs',
      //   correctAnswer: 'Rouge',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/batman.jpg'),
      //   image2: require('./data/Biere/batman2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel est le principal vilain de "Batman Returns" ?',
      //   choices: ['The Joker', 'The Penguin', 'L\'Homme Mystère', 'Bane'],
      //   type: 'MCQs',
      //   correctAnswer: 'The Penguin',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/carpenter.jpg'),
      //   image2: require('./data/Biere/carpenter2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel film ne fait pas partie de la trilogie de l\'Apocalypse de John Carpenter ?',
      //   choices: ['Fog (1980)', 'The Thing (1982)', 'Prince des ténèbres (1987)', 'L\'antre de la folie (1995)'],
      //   type: 'MCQs',
      //   correctAnswer: 'Fog (1980)',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/bond.jpg'),
      //   image2: require('./data/Biere/bond2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel acteur interpréta l\'agent 007 dans le film "Die Another Day ?"',
      //   choices: ['Daniel Craig', 'Pierce Brosnan', 'George Lazenby', 'Sean Connery'],
      //   type: 'MCQs',
      //   correctAnswer: 'Pierce Brosnan',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/starwars.jpg'),
      //   image2: require('./data/Biere/starwars2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Dans quel film, l\'Amiral Ackbar prononce "It\'s a trap !" ?',
      //   choices: ['Star Wars - Empire strikes back', 'Star Trek - The Final Frontier', 'Star Wars - Rogue One', 'Star Wars - Return of the Jedi'],
      //   type: 'MCQs',
      //   correctAnswer: 'Star Wars - Return of the Jedi',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/shaun.jpg'),
      //   image2: require('./data/Biere/shaun.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Qui a réalisé le film "Shaun of the Dead" ?',
      //   choices: ['Richard Donner', 'Edgar Wright', 'Stanley Kubrick', 'Carol Reed'],
      //   type: 'MCQs',
      //   correctAnswer: 'Edgar Wright',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/asylum.jpg'),
      //   image2: require('./data/Biere/2012.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel film n\'a pas été produit par la compagnie The Asylum ?',
      //   choices: ['2012', 'Halloween Night', 'Transmorphers', 'Titanic II', 'Paranormal Entity', 'Age of the Hobbits', 'Sharknado', 'Alien Convergence ' ],
      //   type: 'MCQs',
      //   correctAnswer: '2012',
      //   explication: '',
      // },
    ],
    Internet: [
      {
        theme: 'Internet',
        image: require('./data/Internet/zen.jpeg'),
        image2: require('./data/Internet/zen2.png'),
        video: '',
        video2: '',
        question: 'Qui sont les 2 présentateurs du late show Zen sur Twitch ?',
        choices: ['Amixem et Moustache', 'Fred et Seb du Grenier', 'Maxime Biaggi et Grimkujow', 'Domingo et Kleman'],
        type: 'MCQs',
        correctAnswer: 'Maxime Biaggi et Grimkujow',
        explication: '',
      },
      {
        theme: 'Internet',
        image: require('./data/Internet/apanyan.jpg'),
        image2: require('./data/Internet/apanyan.jpg'),
        video: '',
        video2: '',
        question: 'T\'as les crampté ?',
        choices: ['Apanyan', 'Feur', 'Quoicoubaka', 'Dant Cousteau'],
        type: 'MCQs',
        correctAnswer: 'Apanyan',
        explication: '',
      },
      {
        theme: 'Internet',
        image: require('./data/Internet/pokemon_pikachu.png'),
        image2: require('./data/Internet/pokemon_pikachu2.png'),
        video: '',
        video2: '',
        question: 'Who\'s that Pokemon ?',
        choices: ['Pikachu', 'Bulbizarre', 'Carapuce', 'Salamèche'],
        type: 'MCQs',
        correctAnswer: 'Pikachu',
        explication: '',
      },
      {
        theme: 'Internet',
        image: require('./data/Internet/gentle.jpg'),
        image2: require('./data/Internet/gentle2.jpg'),
        video: '',
        video2: '',
        question: 'Qui ne fait pas partie des Gentlemates ?',
        choices: ['Squeezie', 'Gotaga', 'Brawks', 'DFG'],
        type: 'MCQs',
        correctAnswer: 'DFG',
        explication: '',
      },
      {
        theme: 'Internet',
        image: require('./data/Internet/pokemon_virus.png'),
        image2: require('./data/Internet/pokemon_virus2.png'),
        video: '',
        video2: '',
        question: 'Who\'s that Pokemon ?',
        choices: ['Racaillou', 'Smogo', 'Mine navale', 'COVID'],
        type: 'MCQs',
        correctAnswer: 'COVID',
        explication: '',
      },
      {
        theme: 'Internet',
        image: require('./data/Internet/allstar.jpg'),
        image2: require('./data/Internet/allstar2.jpg'),
        video: '',
        video2: '',
        question: 'Qui n\'a pas fait partie de la sélection de l\'équipe de France au match Eleven All Stars face aux Espagnols, organisé par Aminematue ?',
        choices: ['Lebouseuh', 'Zack Nani', 'Billy RebeuDeter', 'DFG', 'Carlito', 'Rivenzi'],
        type: 'MCQs',
        correctAnswer: 'DFG',
        explication: '',
      },
      {
        theme: 'Internet',
        image: require('./data/Internet/rance.jpeg'),
        image2: require('./data/Internet/rance2.png'),
        video: '',
        video2: '',
        question: 'En quelle langue doit-on parler sur le Reddit /r/rance ?',
        choices: ['Vichyssois', 'Rançois', 'Rance', 'Rançais' ],
        type: 'MCQs',
        correctAnswer: 'Rançais',
        explication: '',
      },
      {
        theme: 'Internet',
        image: require('./data/Internet/pokemon_jigg.png'),
        image2: require('./data/Internet/pokemon_jigg2.png'),
        video: '',
        video2: '',
        question: 'Who\'s that Pokemon ?',
        choices: ['Voltorbe', 'Rondoudou', 'Bouldeneu', 'Saitama (One Punch Man)' ],
        type: 'MCQs',
        correctAnswer: 'Rondoudou',
        explication: '',
      },

    ],
    Series: [
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/annihilation.jpg'),
      //   image2: require('./data/Biere/annihilation2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Vrai ou Faux ? Le film "Annihilation" de Alex Garland de 2018 est une adaptation de la nouvelle "The Colour Out of Space" de HP Lovecraft parue en 1927',
      //   choices: ['Vrai', 'Faux'],
      //   type: 'MCQs',
      //   correctAnswer: 'Faux',
      //   explication: 'Le film est une adaption de la nouvelle "Annihilation" parue en 2014 de Jeff VanderMeer',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/matrix.jpg'),
      //   image2: require('./data/Biere/matrix.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Dans le premier film "The Matrix", quelle pilule permet de sortir de la matrice ?',
      //   choices: ['Rouge', 'Bleue'],
      //   type: 'MCQs',
      //   correctAnswer: 'Rouge',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/batman.jpg'),
      //   image2: require('./data/Biere/batman2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel est le principal vilain de "Batman Returns" ?',
      //   choices: ['The Joker', 'The Penguin', 'L\'Homme Mystère', 'Bane'],
      //   type: 'MCQs',
      //   correctAnswer: 'The Penguin',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/carpenter.jpg'),
      //   image2: require('./data/Biere/carpenter2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel film ne fait pas partie de la trilogie de l\'Apocalypse de John Carpenter ?',
      //   choices: ['Fog (1980)', 'The Thing (1982)', 'Prince des ténèbres (1987)', 'L\'antre de la folie (1995)'],
      //   type: 'MCQs',
      //   correctAnswer: 'Fog (1980)',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/bond.jpg'),
      //   image2: require('./data/Biere/bond2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel acteur interpréta l\'agent 007 dans le film "Die Another Day ?"',
      //   choices: ['Daniel Craig', 'Pierce Brosnan', 'George Lazenby', 'Sean Connery'],
      //   type: 'MCQs',
      //   correctAnswer: 'Pierce Brosnan',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/starwars.jpg'),
      //   image2: require('./data/Biere/starwars2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Dans quel film, l\'Amiral Ackbar prononce "It\'s a trap !" ?',
      //   choices: ['Star Wars - Empire strikes back', 'Star Trek - The Final Frontier', 'Star Wars - Rogue One', 'Star Wars - Return of the Jedi'],
      //   type: 'MCQs',
      //   correctAnswer: 'Star Wars - Return of the Jedi',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/shaun.jpg'),
      //   image2: require('./data/Biere/shaun.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Qui a réalisé le film "Shaun of the Dead" ?',
      //   choices: ['Richard Donner', 'Edgar Wright', 'Stanley Kubrick', 'Carol Reed'],
      //   type: 'MCQs',
      //   correctAnswer: 'Edgar Wright',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/asylum.jpg'),
      //   image2: require('./data/Biere/2012.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel film n\'a pas été produit par la compagnie The Asylum ?',
      //   choices: ['2012', 'Halloween Night', 'Transmorphers', 'Titanic II', 'Paranormal Entity', 'Age of the Hobbits', 'Sharknado', 'Alien Convergence ' ],
      //   type: 'MCQs',
      //   correctAnswer: '2012',
      //   explication: '',
      // },

    ],
    JeuxVideos: [
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/annihilation.jpg'),
      //   image2: require('./data/Biere/annihilation2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Vrai ou Faux ? Le film "Annihilation" de Alex Garland de 2018 est une adaptation de la nouvelle "The Colour Out of Space" de HP Lovecraft parue en 1927',
      //   choices: ['Vrai', 'Faux'],
      //   type: 'MCQs',
      //   correctAnswer: 'Faux',
      //   explication: 'Le film est une adaption de la nouvelle "Annihilation" parue en 2014 de Jeff VanderMeer',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/matrix.jpg'),
      //   image2: require('./data/Biere/matrix.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Dans le premier film "The Matrix", quelle pilule permet de sortir de la matrice ?',
      //   choices: ['Rouge', 'Bleue'],
      //   type: 'MCQs',
      //   correctAnswer: 'Rouge',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/batman.jpg'),
      //   image2: require('./data/Biere/batman2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel est le principal vilain de "Batman Returns" ?',
      //   choices: ['The Joker', 'The Penguin', 'L\'Homme Mystère', 'Bane'],
      //   type: 'MCQs',
      //   correctAnswer: 'The Penguin',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/carpenter.jpg'),
      //   image2: require('./data/Biere/carpenter2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel film ne fait pas partie de la trilogie de l\'Apocalypse de John Carpenter ?',
      //   choices: ['Fog (1980)', 'The Thing (1982)', 'Prince des ténèbres (1987)', 'L\'antre de la folie (1995)'],
      //   type: 'MCQs',
      //   correctAnswer: 'Fog (1980)',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/bond.jpg'),
      //   image2: require('./data/Biere/bond2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel acteur interpréta l\'agent 007 dans le film "Die Another Day ?"',
      //   choices: ['Daniel Craig', 'Pierce Brosnan', 'George Lazenby', 'Sean Connery'],
      //   type: 'MCQs',
      //   correctAnswer: 'Pierce Brosnan',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/starwars.jpg'),
      //   image2: require('./data/Biere/starwars2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Dans quel film, l\'Amiral Ackbar prononce "It\'s a trap !" ?',
      //   choices: ['Star Wars - Empire strikes back', 'Star Trek - The Final Frontier', 'Star Wars - Rogue One', 'Star Wars - Return of the Jedi'],
      //   type: 'MCQs',
      //   correctAnswer: 'Star Wars - Return of the Jedi',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/shaun.jpg'),
      //   image2: require('./data/Biere/shaun.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Qui a réalisé le film "Shaun of the Dead" ?',
      //   choices: ['Richard Donner', 'Edgar Wright', 'Stanley Kubrick', 'Carol Reed'],
      //   type: 'MCQs',
      //   correctAnswer: 'Edgar Wright',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/asylum.jpg'),
      //   image2: require('./data/Biere/2012.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel film n\'a pas été produit par la compagnie The Asylum ?',
      //   choices: ['2012', 'Halloween Night', 'Transmorphers', 'Titanic II', 'Paranormal Entity', 'Age of the Hobbits', 'Sharknado', 'Alien Convergence ' ],
      //   type: 'MCQs',
      //   correctAnswer: '2012',
      //   explication: '',
      // },

    ],
    GD: [
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/annihilation.jpg'),
      //   image2: require('./data/Biere/annihilation2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Vrai ou Faux ? Le film "Annihilation" de Alex Garland de 2018 est une adaptation de la nouvelle "The Colour Out of Space" de HP Lovecraft parue en 1927',
      //   choices: ['Vrai', 'Faux'],
      //   type: 'MCQs',
      //   correctAnswer: 'Faux',
      //   explication: 'Le film est une adaption de la nouvelle "Annihilation" parue en 2014 de Jeff VanderMeer',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/matrix.jpg'),
      //   image2: require('./data/Biere/matrix.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Dans le premier film "The Matrix", quelle pilule permet de sortir de la matrice ?',
      //   choices: ['Rouge', 'Bleue'],
      //   type: 'MCQs',
      //   correctAnswer: 'Rouge',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/batman.jpg'),
      //   image2: require('./data/Biere/batman2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel est le principal vilain de "Batman Returns" ?',
      //   choices: ['The Joker', 'The Penguin', 'L\'Homme Mystère', 'Bane'],
      //   type: 'MCQs',
      //   correctAnswer: 'The Penguin',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/carpenter.jpg'),
      //   image2: require('./data/Biere/carpenter2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel film ne fait pas partie de la trilogie de l\'Apocalypse de John Carpenter ?',
      //   choices: ['Fog (1980)', 'The Thing (1982)', 'Prince des ténèbres (1987)', 'L\'antre de la folie (1995)'],
      //   type: 'MCQs',
      //   correctAnswer: 'Fog (1980)',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/bond.jpg'),
      //   image2: require('./data/Biere/bond2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel acteur interpréta l\'agent 007 dans le film "Die Another Day ?"',
      //   choices: ['Daniel Craig', 'Pierce Brosnan', 'George Lazenby', 'Sean Connery'],
      //   type: 'MCQs',
      //   correctAnswer: 'Pierce Brosnan',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/starwars.jpg'),
      //   image2: require('./data/Biere/starwars2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Dans quel film, l\'Amiral Ackbar prononce "It\'s a trap !" ?',
      //   choices: ['Star Wars - Empire strikes back', 'Star Trek - The Final Frontier', 'Star Wars - Rogue One', 'Star Wars - Return of the Jedi'],
      //   type: 'MCQs',
      //   correctAnswer: 'Star Wars - Return of the Jedi',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/shaun.jpg'),
      //   image2: require('./data/Biere/shaun.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Qui a réalisé le film "Shaun of the Dead" ?',
      //   choices: ['Richard Donner', 'Edgar Wright', 'Stanley Kubrick', 'Carol Reed'],
      //   type: 'MCQs',
      //   correctAnswer: 'Edgar Wright',
      //   explication: '',
      // },
      // {
      //   theme: 'Biere',
      //   image: require('./data/Biere/asylum.jpg'),
      //   image2: require('./data/Biere/2012.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel film n\'a pas été produit par la compagnie The Asylum ?',
      //   choices: ['2012', 'Halloween Night', 'Transmorphers', 'Titanic II', 'Paranormal Entity', 'Age of the Hobbits', 'Sharknado', 'Alien Convergence ' ],
      //   type: 'MCQs',
      //   correctAnswer: '2012',
      //   explication: '',
      // },

    ],
    Cocktail: [
      {
        theme: 'Cocktail',
        image: require('./data/Cocktail/tails.jpg'),
        image2: require('./data/Cocktail/tails.jpg'),
        video: '',
        video2: '',
        question: 'Que signifie CockTail ?',
        choices: ['Une queue de bite', 'La bite de Tails', 'Une bite de queue', 'Une queue à bites', 'Une bite à queues'],
        type: 'MCQs',
        correctAnswer: 'Une queue à bites',
        explication: '',
      },
      // {
      //   theme: 'Cocktail',
      //   image: require('./data/Cocktail/matrix.jpg'),
      //   image2: require('./data/Cocktail/matrix.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Dans le premier film "The Matrix", quelle pilule permet de sortir de la matrice ?',
      //   choices: ['Rouge', 'Bleue'],
      //   type: 'MCQs',
      //   correctAnswer: 'Rouge',
      //   explication: '',
      // },
      // {
      //   theme: 'Cocktail',
      //   image: require('./data/Cocktail/batman.jpg'),
      //   image2: require('./data/Cocktail/batman2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel est le principal vilain de "Batman Returns" ?',
      //   choices: ['The Joker', 'The Penguin', 'L\'Homme Mystère', 'Bane'],
      //   type: 'MCQs',
      //   correctAnswer: 'The Penguin',
      //   explication: '',
      // },
      // {
      //   theme: 'Cocktail',
      //   image: require('./data/Cocktail/carpenter.jpg'),
      //   image2: require('./data/Cocktail/carpenter2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel film ne fait pas partie de la trilogie de l\'Apocalypse de John Carpenter ?',
      //   choices: ['Fog (1980)', 'The Thing (1982)', 'Prince des ténèbres (1987)', 'L\'antre de la folie (1995)'],
      //   type: 'MCQs',
      //   correctAnswer: 'Fog (1980)',
      //   explication: '',
      // },
      // {
      //   theme: 'Cocktail',
      //   image: require('./data/Cocktail/bond.jpg'),
      //   image2: require('./data/Cocktail/bond2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel acteur interpréta l\'agent 007 dans le film "Die Another Day ?"',
      //   choices: ['Daniel Craig', 'Pierce Brosnan', 'George Lazenby', 'Sean Connery'],
      //   type: 'MCQs',
      //   correctAnswer: 'Pierce Brosnan',
      //   explication: '',
      // },
      // {
      //   theme: 'Cocktail',
      //   image: require('./data/Cocktail/starwars.jpg'),
      //   image2: require('./data/Cocktail/starwars2.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Dans quel film, l\'Amiral Ackbar prononce "It\'s a trap !" ?',
      //   choices: ['Star Wars - Empire strikes back', 'Star Trek - The Final Frontier', 'Star Wars - Rogue One', 'Star Wars - Return of the Jedi'],
      //   type: 'MCQs',
      //   correctAnswer: 'Star Wars - Return of the Jedi',
      //   explication: '',
      // },
      // {
      //   theme: 'Cocktail',
      //   image: require('./data/Cocktail/shaun.jpg'),
      //   image2: require('./data/Cocktail/shaun.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Qui a réalisé le film "Shaun of the Dead" ?',
      //   choices: ['Richard Donner', 'Edgar Wright', 'Stanley Kubrick', 'Carol Reed'],
      //   type: 'MCQs',
      //   correctAnswer: 'Edgar Wright',
      //   explication: '',
      // },
      // {
      //   theme: 'Cocktail',
      //   image: require('./data/Cocktail/asylum.jpg'),
      //   image2: require('./data/Cocktail/2012.jpg'),
      //   video: '',
      //   video2: '',
      //   question: 'Quel film n\'a pas été produit par la compagnie The Asylum ?',
      //   choices: ['2012', 'Halloween Night', 'Transmorphers', 'Titanic II', 'Paranormal Entity', 'Age of the Hobbits', 'Sharknado', 'Alien Convergence ' ],
      //   type: 'MCQs',
      //   correctAnswer: '2012',
      //   explication: '',
      // },

    ],
    Asylum: [
      {
        theme: 'Asylum',
        image: require('./data/Asylum/mars.jpg'),
        image2: require('./data/Asylum/mars2.jpg'),
        video: '',
        video2: '',
        question: 'Quel est l\'oeuvre originale de cette contrefaçon Asylum ?',
        choices: ['Prince of Persia', 'Avatar', 'La Momie', 'Dune'],
        type: 'MCQs',
        correctAnswer: 'Avatar',
        explication: '',
      },
      {
        theme: 'Asylum',
        image: require('./data/Asylum/allan.jpg'),
        image2: require('./data/Asylum/allan2.jpg'),
        video: '',
        video2: '',
        question: 'Quel est l\'oeuvre originale de cette contrefaçon Asylum ?',
        choices: ['Indiana Jones et le Royaume du crâne de cristal', 'Jumanji', 'National Treasure', 'Uncharted'],
        type: 'MCQs',
        correctAnswer: 'Indiana Jones et le Royaume du crâne de cristal',
        explication: '',
      },
      {
        theme: 'Asylum',
        image: require('./data/Asylum/10000.jpeg'),
        image2: require('./data/Asylum/100002.jpg'),
        video: '',
        video2: '',
        question: 'Quel est l\'oeuvre originale de cette contrefaçon Asylum ?',
        choices: ['Jurassic Park', 'Jurassic World', '10000', 'King Kong'],
        type: 'MCQs',
        correctAnswer: '10000',
        explication: '',
      },
      {
        theme: 'Asylum',
        image: require('./data/Asylum/jurassic.jpg'),
        image2: require('./data/Asylum/jurassic2.jpg'),
        video: '',
        video2: '',
        question: 'Quel est l\'oeuvre originale de cette contrefaçon Asylum ?',
        choices: ['Jurassic Park', 'Jurassic World', 'King Kong', 'High School Musical'],
        type: 'MCQs',
        correctAnswer: 'Jurassic World',
        explication: '',
      },
      {
        theme: 'Asylum',
        image: require('./data/Asylum/200.jpg'),
        image2: require('./data/Asylum/2002.jpg'),
        video: '',
        video2: '',
        question: 'Quel est l\'oeuvre originale de cette contrefaçon Asylum ?',
        choices: ['Fast and Furious', 'Drive', 'Need for speed', 'Cars'],
        type: 'MCQs',
        correctAnswer: 'Fast and Furious',
        explication: '',
      },
      {
        theme: 'Asylum',
        image: require('./data/Asylum/milf.jpg'),
        image2: require('./data/Asylum/milf2.jpg'),
        video: '',
        video2: '',
        question: 'Quel est l\'oeuvre originale de cette contrefaçon Asylum ?',
        choices: ['Euro Trip', 'American Pie', 'The Girl Next Door', 'The 40-year-old Virgin'],
        type: 'MCQs',
        correctAnswer: 'American Pie',
        explication: '',
      },
      {
        theme: 'Asylum',
        image: require('./data/Asylum/abraham.jpg'),
        image2: require('./data/Asylum/abraham2.jpg'),
        video: '',
        video2: '',
        question: 'Quel est l\'oeuvre originale de cette contrefaçon Asylum ?',
        choices: ['Underworld', 'Resident Evil', 'Abraham Lincoln chasseur de Vampires', 'La Défense Lincoln'],
        type: 'MCQs',
        correctAnswer: 'Abraham Lincoln chasseur de Vampires',
        explication: '',
      },
      {
        theme: 'Asylum',
        image: require('./data/Asylum/shark.jpg'),
        image2: require('./data/Asylum/shark2.jpg'),
        video: '',
        video2: '',
        question: 'Quel est l\'oeuvre originale de cette contrefaçon Asylum ?',
        choices: ['La planète des singes', 'Les dents de la mer', 'Sharknado', 'Fantastic Planet' ],
        type: 'MCQs',
        correctAnswer: 'La planète des singes',
        explication: '',
      },
    ],
    Fusion: [
      {
        theme: 'Fusion',
        image: require('./data/Fusion/thomas.png'),
        image2: require('./data/Fusion/thomas2.png'),
        video: '',
        video2: '',
        question: 'Avec qui Son Goku a fusionné ?',
        choices: ['Chuggington', 'Thomas the tank engine', 'The Little Engine That Could', 'Ivor the Engine'],
        type: 'MCQs',
        correctAnswer: 'Thomas the tank engine',
        explication: '',
      },
      {
        theme: 'Fusion',
        image: require('./data/Fusion/sailor.png'),
        image2: require('./data/Fusion/sailor2.png'),
        video: '',
        video2: '',
        question: 'Avec qui Son Goku a fusionné ?',
        choices: ['CardCaptor Sakura', 'Haruhi Suzumiya', 'Sailor Moon', 'Yui Hirasawa (K-ON!)'],
        type: 'MCQs',
        correctAnswer: 'Sailor Moon',
        explication: '',
      },
      {
        theme: 'Fusion',
        image: require('./data/Fusion/geralt.png'),
        image2: require('./data/Fusion/geralt2.png'),
        video: '',
        video2: '',
        question: 'Avec qui Son Goku a fusionné ?',
        choices: ['Cloud Strife (FF)', 'Geralt de Riv (The Witcher)', 'Kratos (God of War)', 'Altair (Assassin\'s Creed'],
        type: 'MCQs',
        correctAnswer: 'Geralt de Riv (The Witcher)',
        explication: '',
      },
      {
        theme: 'Fusion',
        image: require('./data/Fusion/elsa.png'),
        image2: require('./data/Fusion/elsa2.png'),
        video: '',
        video2: '',
        question: 'Avec qui Vegeta a fusionné ?',
        choices: ['Elsa (Reine des neiges)', 'Harmonie (Super Mario Galaxy)', 'Belle (La Belle et la Bête', 'Cendrillon'],
        type: 'MCQs',
        correctAnswer: 'Elsa (Reine des neiges)',
        explication: '',
      },
      {
        theme: 'Fusion',
        image: require('./data/Fusion/bob.png'),
        image2: require('./data/Fusion/bob2.png'),
        video: '',
        video2: '',
        question: 'Avec qui Bob l\'éponge a fusionné ?',
        choices: ['Pikachu', 'Pohm', 'Hamtaro', 'Raichu'],
        type: 'MCQs',
        correctAnswer: 'Pikachu',
        explication: '',
      },
      {
        theme: 'Fusion',
        image: require('./data/Fusion/mcdo.png'),
        image2: require('./data/Fusion/mcdo2.png'),
        video: '',
        video2: '',
        question: 'Avec qui Son Goku a fusionné ?',
        choices: ['Ca', 'Le Joker', 'Krusty le Clown', 'Ronald McDonald'],
        type: 'MCQs',
        correctAnswer: 'Ronald McDonald',
        explication: '',
      },
      {
        theme: 'Fusion',
        image: require('./data/Fusion/gel.png'),
        image2: require('./data/Fusion/gel2.png'),
        video: '',
        video2: '',
        question: 'Avec qui Son Goku a fusionné ?',
        choices: ['Un flacon de savon', 'Un flacon de lessive liquide', 'Un flacon de gel hydroalcolique', 'Un flacon de dentifrice'],
        type: 'MCQs',
        correctAnswer: 'Un flacon de gel hydroalcolique',
        explication: '',
      },
      {
        theme: 'Fusion',
        image: require('./data/Fusion/xbox.png'),
        image2: require('./data/Fusion/xbox2.png'),
        video: '',
        video2: '',
        question: 'Avec qui Vegeta a fusionné ?',
        choices: ['Le COVID', 'Xbox One', 'Un déchet radioactif', 'Green Lanterne (Ligue des Justiciers)' ],
        type: 'MCQs',
        correctAnswer: 'Xbox One',
        explication: '',
      },
    ]}
  }